### ISSUE TITLE
Playlist not working on Tivimate

### ISSUE THREAD

**Issue by AlfonsoBussalleu** [jsosao/m3u#1]
Hi jsosao
The m3u8 list below works on other players (most of the channels) but when I try to watch them on TIVIMATE on Firestick most of them don’t work, error 401 not found
http://github.com/jsosao/m3u/raw/main/mylist.m3u8
Can you please check and advise

**Comment by AlfonsoBussalleu** [comment]
Probably is the file format (m3u8), may need a m3u.

**Comment by jsosao** [comment]
Hi, I don't know how I can help you.
