### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by XiaErr** [jsosao/m3u#5]
Hello.

I just wanted to give you my sincere thanks for sharing this resource with us all.

Personally i don't watch TV very much but my mother loves it and recently i managed to use the IPTV function on her TV by hocking it to a generic tv box.

Since then i have been searching for iptv lists in m3u format containing good channels and you provided just that... My mother specially loves to watch series and soap operas and she has been very happy since i used your links to give her the opportunity to watch channels like " Universal "  "Telemundo "  " TNT " and other channels that most of the time only come with a cable subscription or something. ( and you also provide then in latin american language which is excellent since that's my mother native language )

So i appreciate very much the fact that you go around collecting the signals of these channels to share it here.

Please keep up the good work and if possible maintain or update the list from time to time in the eventually that a channel comes down or something.

Thanks again for everything you have done.

**Comment by jsosao** [comment]
Tnks
