### ISSUE TITLE
dpelicula

### ISSUE THREAD

**Issue by AussyLatin** [jsosao/m3u#6]
Hi thanks for your share. much appreciated, Dpelicula links does not work at all..

**Comment by AussyLatin** [comment]
Hi, Can we request a Channel??

**Comment by jsosao** [comment]
Cuál ?

**Comment by AussyLatin** [comment]
Aljazeera and El Salvador Channels 4 y 10. thank you..

**Comment by jsosao** [comment]
Done, except Chanel 10, only 4,6 and 12

**Comment by AussyLatin** [comment]
thank you so much

**Comment by AussyLatin** [comment]
Good day, would there be any channel for boxing in the list?? or on the sport m3u. Thank you for your share..

**Comment by Asttaroth13** [comment]
Hola buen dia, mira es que la mayoria de canales no se si estan caidos pero no funcionan hasta hace un rato tipo 1 hora o asi funcionaba correctamente pero ya no funcionan la mayoria. 
muchas gracias por tu atencion

**Comment by jsosao** [comment]
A excepción de los grupales (deportivos), la mayoría funciona correctamente

**Comment by Asttaroth13** [comment]
Si, he visto que los deportivos como ESPN, La liga etc no cargan, pero hbo y demás canales tampoco se quedan colgados, por ahora golden mx funciona correctamente, tal vez sea un error temporal pero espero se pueda solucionar pronto, igual muchas gracias por traernos estas listas en verdad son muy buenas estaré atento a ver si funcionan nuevamente

**Comment by Asttaroth13** [comment]
Ah una cosa más utilizo el reproductor VLC en la pc, crees que tal vez también fallen por eso? Sabes de alguna otra app que sea más compatible?
