### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JJAR2** [jsosao/m3u#8]
#EXTINF:-1 group-title="Bics FANTASTIC",CO: CARACOL	
https://mserver.fantasticiptv.club:8888/FANTASTIC/fcgaNeHS2X/455
Link down together with others, apparently from the same list "FANTASTIC"

**Comment by Joelcgx** [comment]
> #EXTINF:-1 group-title="Bics FANTASTIC",CO: CARACOL https://mserver.fantasticiptv.club:8888/FANTASTIC/fcgaNeHS2X/455 Link down together with others, apparently from the same list "FANTASTIC"

Yes, all channels, this group is inactive.
